# Seek hammer and hanging man.

[config]
date_begin="2014-01-01"
date_end="2017-09-29"
travel_type = "watch"

[[policy]]
name="SeekCandle"
weight=10
[policy.params]
#candle_pattern="engulfing"
candle_pattern="hammer"



[log]
path="/Users/healer/Projects/fregata.d/seeks"
